{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clamm-bot.fullname" . }}-config
data:
{{- range $key, $value := .Values.config.data }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}
{{- end }}
