apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clamm-bot.fullname" . }}-config
  labels:
    {{- include "clamm-bot.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "rebalanceThresholdPercent": 95,
      "osmosisPool": {
        "id": "",
        "token0": "",
        "token1": "",
        "tickSpacing": 0,
        "spreadFactor": 0
      },
      "osmosisPosition": {
        "id": "",
        "bandPercentage": 1
      }
    }