apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clamm-bot.fullname" . }}
  labels:
    {{- include "clamm-bot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "clamm-bot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "clamm-bot.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 120
      serviceAccountName: {{ include "clamm-bot.serviceAccountName" . }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      # --- Copy the config file into the writable volume before running the app ---
      initContainers:
        - name: copy-config
          image: alpine:3.20
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              mkdir -p /pvc/reports /pvc/docker-files/config
              chown -R 1001:1001 /pvc
          volumeMounts:
            - name: data
              mountPath: /pvc

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.command }}
          command: {{ .Values.command }}
          {{- end }}
          {{- if .Values.args }}
          args: {{ .Values.args }}
          {{- end }}
          envFrom:
            {{- range $secretName, $secretData := .Values.secrets }}
            {{- if $secretData.enabled }}
            - secretRef:
                name:  {{ include "clamm-bot.fullname" $ }}-{{ $secretName }}
            {{- end }}
            {{- end }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}

          {{- /* ---- Liveness ---- */}}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- if eq .Values.livenessProbe.type "http" }}
            httpGet: {{- toYaml .Values.livenessProbe.httpGet | nindent 14 }}
            {{- else if eq .Values.livenessProbe.type "tcp" }}
            tcpSocket: {{- toYaml .Values.livenessProbe.tcpSocket | nindent 14 }}
            {{- else if eq .Values.livenessProbe.type "exec" }}
            exec: {{- toYaml .Values.livenessProbe.exec | nindent 14 }}
            {{- end }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
          {{- end }}

          {{- /* ---- Readiness ---- */}}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- if eq .Values.readinessProbe.type "http" }}
            httpGet: {{- toYaml .Values.readinessProbe.httpGet | nindent 14 }}
            {{- else if eq .Values.readinessProbe.type "tcp" }}
            tcpSocket: {{- toYaml .Values.readinessProbe.tcpSocket | nindent 14 }}
            {{- else if eq .Values.readinessProbe.type "exec" }}
            exec: {{- toYaml .Values.readinessProbe.exec | nindent 14 }}
            {{- end }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
              # {{- $root := . -}}
              # {{- if .Values.persistence }}
              # {{- $names := keys .Values.persistence | sortAlpha -}}
              # {{- range $name := $names }}
              # {{- $cfg := index $root.Values.persistence $name }}
              # - name: {{ $name }}
              #   mountPath: {{ default (printf "/data/%s" $name) $cfg.mountPath }}
              # {{- end }}
              # {{- end }}
              # - name: config-volume
              #   mountPath: {{ .Values.configMountPath }}
              #   readOnly: false
              #   subPath: config.json

              # mount some subdirs from the same PVC
              - name: data
                mountPath: /app/reports
                subPath: reports
              - name: data
                mountPath: /app/docker-files/config
                subPath: docker-files/config
      volumes:
        {{- $root := . -}}
        {{- if .Values.persistence }}
        {{- $names := keys .Values.persistence | sortAlpha -}}
        {{- range $name := $names }}
        - name: {{ $name }}
          persistentVolumeClaim:
            claimName: {{ include "clamm-bot.fullname" $root }}-{{ $name }}
        {{- end }}
        {{- end }}

      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
