{{- range $secretName, $secretConfig := .Values.secrets }}
{{- if $secretConfig.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clamm-bot.fullname" $ }}-{{ $secretName }}
  labels:
    {{- include "clamm-bot.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := $secretConfig.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
