replicaCount: 1

image:
  pullPolicy: IfNotPresent

imagePullSecrets:
  - gh-registry-secret

nameOverride: ""
fullnameOverride: "clammbot-prod"

serviceAccount:
  create: true
  annotations: {}
  name: ""

env:
  NODE_ENV: "production"
  IS_DOCKER_RUN: "true"
  # WATCH_FREQUENCY will be set from GitHub Actions

secrets:
  app-secrets:
    enabled: true
    data:
      # These will be set from GitHub Actions
      MNEMONIC: ""
      OSMOSIS_POOL_ID: ""
      REBALANCE_THRESHOLD_PERCENT: ""
      OSMOSIS_POSITION_BAND_PERCENTAGE: ""
      WATCH_FREQUENCY: ""

healthCheck:
  initialDelaySeconds: 120
  periodSeconds: 60
  timeoutSeconds: 10
  failureThreshold: 3

persistence:
  database:
    size: 5Gi
    storageClass: standard-rwo

resources:
  limits:
    cpu: 400m
    memory: 512Gi
  requests:
    cpu: 200m
    memory: 256Mi

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

config:
  enabled: true
  name: app-config
  data:
    config.json: |
      {
        "rebalanceThresholdPercent": 95,
        "osmosisPool": {
          "id": "1282",
          "token0": "ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2",
          "token1": "ibc/498A0751C798A0D9A389AA3691123DADA57DAA4FE165D5C75894505B876BA6E4",
          "tickSpacing": 100,
          "spreadFactor": 0.0005
        },
        "osmosisPosition": {
          "id": "",
          "bandPercentage": 1
        }
      }

configMountPath: /app/config.json
